# AI测试平台 - Prompt模块
# 导出所有Prompt供平台使用

from .test_case_generator import (
    GENERAL_TEST_CASE_PROMPT,
    API_TEST_CASE_PROMPT,
    API_TEST_REPORT_PROMPT,
)

from .ios_simulator_test import (
    IOS_UI_TEST_CASE_PROMPT,
    IOS_TEST_CODE_GENERATOR_PROMPT,
    IOS_TEST_REPORT_PROMPT,
    IOS_SIMULATOR_COMMAND_PROMPT,
)

from .system_prompts import (
    PLATFORM_SYSTEM_PROMPT,
    REQUIREMENT_ANALYSIS_PROMPT,
    TEST_DATA_GENERATION_PROMPT,
    ERROR_ANALYSIS_PROMPT,
)

__all__ = [
    # 测试用例生成
    'GENERAL_TEST_CASE_PROMPT',
    'API_TEST_CASE_PROMPT',
    'API_TEST_REPORT_PROMPT',

    # iOS模拟器测试
    'IOS_UI_TEST_CASE_PROMPT',
    'IOS_TEST_CODE_GENERATOR_PROMPT',
    'IOS_TEST_REPORT_PROMPT',
    'IOS_SIMULATOR_COMMAND_PROMPT',

    # 系统级Prompt
    'PLATFORM_SYSTEM_PROMPT',
    'REQUIREMENT_ANALYSIS_PROMPT',
    'TEST_DATA_GENERATION_PROMPT',
    'ERROR_ANALYSIS_PROMPT',
]
